"use client"

import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  ArrowRight, 
  GitBranch, 
  ArrowLeft as ArrowLeftIcon, 
  RotateCcw, 
  ExternalLink,
  Layers,
  Navigation,
  Settings,
  Copy,
  Check
} from "lucide-react";
import { useBuilder, builderActions } from "@/lib/builderContext";
import { useToast } from "@/hooks/use-toast";

export function FlowDescriptionCard() {
  const { state, dispatch } = useBuilder();
  const { toast } = useToast();
  const [isGeneratingExport, setIsGeneratingExport] = useState(false);
  const [flowLogicCopied, setFlowLogicCopied] = useState(false);

  const copyFlowLogic = async () => {
    try {
      if (!state.appFlow) {
        toast({
          title: "No flow logic available",
          description: "Please generate the app flow first.",
          variant: "destructive"
        });
        return;
      }
      
      await navigator.clipboard.writeText(state.appFlow.flowLogic);
      setFlowLogicCopied(true);
      toast({
        title: "Copied to clipboard!",
        description: "Flow logic has been copied to your clipboard.",
      });
      
      // Reset the copy state after 2 seconds
      setTimeout(() => {
        setFlowLogicCopied(false);
      }, 2000);
    } catch (err) {
      toast({
        title: "Copy failed",
        description: "Unable to copy to clipboard. Please try again.",
        variant: "destructive"
      });
    }
  };

  const continueToExport = async () => {
    if (!state.appFlow) {
      toast({
        title: "No App Flow Available",
        description: "Please generate the app flow first.",
        variant: "destructive"
      });
      return;
    }

    setIsGeneratingExport(true);
    dispatch(builderActions.setGenerating(true));
    dispatch(builderActions.setGenerationProgress(0));

    // Simulate export generation
    const progressSteps = [
      { progress: 25, delay: 600, message: "Compiling unified prompt..." },
      { progress: 50, delay: 800, message: "Creating screen-by-screen prompts..." },
      { progress: 75, delay: 700, message: "Optimizing for different tools..." },
      { progress: 100, delay: 500, message: "Finalizing export package..." }
    ];

    for (const step of progressSteps) {
      await new Promise(resolve => setTimeout(resolve, step.delay));
      dispatch(builderActions.setGenerationProgress(step.progress));
    }

    // Generate export prompts
    const exportPrompts = {
      unifiedPrompt: generateUnifiedPrompt(),
      screenByScreenPrompts: state.screenPrompts,
      targetTool: 'framer' // Default to Framer
    };

    dispatch(builderActions.setExportPrompts(exportPrompts));
    dispatch(builderActions.setGenerating(false));
    dispatch(builderActions.setCurrentCard(6));
    setIsGeneratingExport(false);

    toast({
      title: "Export Package Ready!",
      description: "Your prompt package is ready for download and use.",
    });
  };

  const generateUnifiedPrompt = () => {
    const appIdea = state.appIdea;
    const blueprint = state.appBlueprint;
    const flow = state.appFlow;

    return `# ${appIdea.appName} - Complete App Specification

## App Overview
${appIdea.ideaDescription}

**Platform(s):** ${appIdea.platforms.join(', ')}
**Design Style:** ${appIdea.designStyle}
**Target Audience:** ${appIdea.targetAudience || 'General users'}

## App Structure
${blueprint?.screens.map((screen, index) => 
  `${index + 1}. **${screen.name}**: ${screen.purpose}`
).join('\n')}

## Navigation Flow
${flow?.flowLogic}

## Screen Transitions
${flow?.screenTransitions.map(transition => `• ${transition}`).join('\n')}

## Conditional Logic
${flow?.conditionalRouting.map(rule => `• ${rule}`).join('\n')}

## Style Guidelines
- Design Style: ${appIdea.designStyle}
- Platform: ${appIdea.platforms.join(' and ')}
${appIdea.styleDescription ? `- Additional Notes: ${appIdea.styleDescription}` : ''}

## User Motivation
${state.validationQuestions.motivation}

---
Generated by Builder Blueprint AI`;
  };

  if (!state.appFlow) {
    return (
      <div className="text-center py-8">
        <GitBranch className="h-12 w-12 text-gray-400 mx-auto mb-4" />
        <h3 className="text-lg font-medium text-gray-300">No App Flow Generated</h3>
        <p className="text-sm text-gray-400">
          Complete the screen prompts generation to create the app flow.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <h3 className="text-lg font-semibold flex items-center justify-center gap-2 text-white">
          <GitBranch className="h-5 w-5 text-blue-400" />
          🧭 App Flow & Wireframe Describer
        </h3>
        <p className="text-sm text-gray-400">
          Navigation logic and screen relationships for your app
        </p>
      </div>

      {/* Flow Logic */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-base text-white">
              <Layers className="h-4 w-4 text-purple-400" />
              Flow Logic
            </CardTitle>
            <Button
              onClick={copyFlowLogic}
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0 hover:bg-white/10"
            >
              {flowLogicCopied ? (
                <Check className="h-4 w-4 text-green-400" />
              ) : (
                <Copy className="h-4 w-4 text-gray-400" />
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="bg-white/10 backdrop-blur-sm p-4 rounded-lg border border-white/10">
            <pre className="text-sm whitespace-pre-wrap font-mono text-gray-300">
              {state.appFlow.flowLogic}
            </pre>
          </div>
        </CardContent>
      </Card>

      {/* Conditional Routing */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-white">
            <GitBranch className="h-4 w-4 text-green-400" />
            Conditional Routing
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {state.appFlow.conditionalRouting.map((rule, index) => (
              <div key={index} className="flex items-start gap-2 p-2 bg-blue-500/20 backdrop-blur-sm rounded border border-blue-500/30">
                <Badge variant="outline" className="mt-0.5 text-xs border-white/20 text-gray-300">
                  {index + 1}
                </Badge>
                <span className="text-sm text-gray-300">{rule}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Back Button Behavior */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-white">
            <ArrowLeftIcon className="h-4 w-4 text-orange-400" />
            Back Button Behavior
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-white/10 backdrop-blur-sm p-3 rounded text-sm text-gray-300 border border-white/10">
            {state.appFlow.backButtonBehavior}
          </div>
        </CardContent>
      </Card>

      {/* Modal Logic */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-white">
            <ExternalLink className="h-4 w-4 text-pink-400" />
            Modal Logic
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-white/10 backdrop-blur-sm p-3 rounded text-sm text-gray-300 border border-white/10">
            {state.appFlow.modalLogic}
          </div>
        </CardContent>
      </Card>

      {/* Screen Transitions */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-white">
            <Navigation className="h-4 w-4 text-cyan-400" />
            Screen Transitions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {state.appFlow.screenTransitions.map((transition, index) => (
              <div key={index} className="flex items-center gap-2 p-2 border border-white/20 rounded bg-white/5 backdrop-blur-sm">
                <Badge variant="secondary" className="text-xs bg-white/10 text-gray-300 border-white/20">
                  {index + 1}
                </Badge>
                <span className="text-sm font-mono text-gray-300">{transition}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Visual Flow Representation */}
      <Card className="bg-black/40 backdrop-blur-sm border-white/10">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-white">
            <RotateCcw className="h-4 w-4 text-teal-400" />
            Visual Flow Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-gradient-to-r from-blue-500/20 to-purple-500/20 p-4 rounded-lg backdrop-blur-sm border border-white/10">
            <div className="text-center space-y-3">
              <div className="flex items-center justify-center gap-2 text-sm">
                <Badge className="bg-green-500/20 text-green-300 border-green-500/30">Start</Badge>
                <ArrowRight className="h-4 w-4 text-gray-400" />
                <Badge variant="secondary" className="bg-white/10 text-gray-300 border-white/20">Authentication</Badge>
                <ArrowRight className="h-4 w-4 text-gray-400" />
                <Badge variant="secondary" className="bg-white/10 text-gray-300 border-white/20">Main App</Badge>
                <ArrowRight className="h-4 w-4 text-gray-400" />
                <Badge className="bg-blue-500/20 text-blue-300 border-blue-500/30">Features</Badge>
              </div>
              <Separator className="bg-white/20" />
              <div className="text-xs text-gray-400">
                Users flow through authentication, land on the main dashboard, and navigate to specific features based on their needs and permissions.
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* App Architecture Summary */}
      <Card className="bg-gradient-to-r from-green-500/20 to-emerald-500/20 backdrop-blur-sm border-green-500/30">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base text-green-300">
            <Settings className="h-4 w-4" />
            Architecture Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
            <div>
              <h5 className="font-medium text-green-300">Screens</h5>
              <p className="text-green-200">{state.appBlueprint?.screens.length || 0} total screens</p>
            </div>
            <div>
              <h5 className="font-medium text-green-300">User Roles</h5>
              <p className="text-green-200">{state.appBlueprint?.userRoles.length || 0} role types</p>
            </div>
            <div>
              <h5 className="font-medium text-green-300">Data Models</h5>
              <p className="text-green-200">{state.appBlueprint?.dataModels.length || 0} data entities</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Continue Button */}
      <div className="flex justify-end pt-4">
        <Button 
          onClick={continueToExport}
          disabled={isGeneratingExport}
          className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white"
          size="lg"
        >
          {isGeneratingExport ? (
            <>
              <div className="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full" />
              Generating Export...
            </>
          ) : (
            <>
              Generate Export Package
              <ArrowRight className="h-4 w-4" />
            </>
          )}
        </Button>
      </div>
    </div>
  );
}
